### ISSUE TITLE
No package matching 'libncurses5:i386' is available error

### ISSUE THREAD

**Issue by martinmicunda** [nickpack/ansible-role-android-sdk#1]
Hi, 

I try use your ansible role in one of my [project](https://github.com/martinmicunda/ionic-photo-gallery/blob/master/ansible%2Fplaybook.yml) but I am getting follow error during provisioning (NOTE I am using trusty64 image in vagrant):

```
TASK: [nickp666.android-sdk | Install build dependencies] ********************* 
failed: [default] => (item=libncurses5:i386,libstdc++6:i386,libgcc1:i386,zlib1g:i386,imagemagick,expect,ant,ccache,autoconf,automake,python-dev,zlibc,android-tools-adb) => {"failed": true, "item": "libncurses5:i386,libstdc++6:i386,libgcc1:i386,zlib1g:i386,imagemagick,expect,ant,ccache,autoconf,automake,python-dev,zlibc,android-tools-adb"}
msg: No package matching 'libncurses5:i386' is available

FATAL: all hosts have already failed -- aborting

```

Thanks

**Comment by nickpack** [comment]
@martinmicunda Hrrrm thats interesting, did the i386 enable step complete successfully?

**Comment by martinmicunda** [comment]
Yes it did..

**Comment by martinmicunda** [comment]
@nickpack never mind somehow i got that working...

**Comment by mattfili** [comment]
@martinmicunda I'm following along with your tutorial and running up on the same issue.  How did you get it working?

**Comment by martinmicunda** [comment]
I got it running by changing lib version see https://github.com/martinmicunda/ionic-photo-gallery/blob/master/ansible/playbook.yml and it was working for me...

**Comment by mattfili** [comment]
@martinmicunda, thanks for the quick response.  I  jumped the gun with my question before looking at your updated ansible file. Everything seemed to work aside from lib32z1 which was generating the error. msg: No package matching 'libncurses5:i386' is available.

I removed that particular dependency and it seems to be provisioning fine.
