### ISSUE TITLE
Latest releases not on Ansible Galaxy

### ISSUE THREAD

**Issue by maurizi** [nickpack/ansible-role-android-sdk#9]
The Github releases page lists the last release of this project as `v0.0.6`, but the [page on ansible Galaxy shows the last release as `v0.0.4`](https://galaxy.ansible.com/nickp666/android-sdk/).

Can you update the Ansible Galaxy entry?

**Comment by nickpack** [comment]
@maurizi Looking at this now.

**Comment by nickpack** [comment]
All done, there was an issue with the platform definitions in the meta preventing it being updated, which I've just fixed.
